---

- name: configure user account
  user:
    name: '{{ user }}'
    shell: /usr/bin/zsh
    groups:
      - plugdev
      - wireshark
      - docker
    append: yes
  become_user: root

- name: install pyenv
  command: curl https://pyenv.run | bash
  args:
    creates: /home/{{ user }}/.pyenv

- name: create dev virtualenv
  pip:
    name: '{{ item }}'
    state: latest
    virtualenv: /home/{{ user }}/.pyenv/versions/dev
    virtualenv_command: pyenv
  with_items:
    - ipython
    - httpie

- name: install tmux settings
  template:
    src: files/tmux.conf
    dest: /home/{{ user }}/.tmux.conf

- name: install ideavimrc
  template:
    src: files/ideavimrc
    dest: /home/{{ user }}/.ideavimrc
