---

- name: installing vim plugins
  command: vim +PluginInstall +qall
  args:
    creates: ~/.dot-files/vim/vim/bundle/ctrlp.vim

- name: creating application preferences directory
  file:
    state: directory
    path: ~/.local/share/applications

- name: making vim the default text editor
  copy:
    src: defaults.list
    dest: ~/.local/share/applications/defaults.list

- name: applying custom keyboard shortcuts
  copy:
    src: xfce4-keyboard-shortcuts.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/

- name: copying compiz settings to ansible file cache
  copy:
    src: compiz.profile
    dest: '~/'
  register: new_compiz_settings
  become_user: root

- name: import compiz settings
  command: python -c "import compizconfig; import os; compizconfig.Context().Import(os.path.expanduser('~/compiz.profile'))"
  when: new_compiz_settings | changed

- name: make compiz the default windows manager
  copy:
    src: xfce4-session.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/

- name: copying over redshift to improve human sleep
  copy:
    src: redshift.conf
    dest: ~/.config/

- name: create handy folder for mounting things
  file:
    state: directory
    path: ~/mnt/
    mode: 0700
