---

- name: fetching personal dotfiles repo
  git:
    repo: '{{ dot_files_repo }}'
    dest: ~/.dot-files

- name: creating links for dotfiles
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - {src: '~/.dot-files/vim/vimrc',         dest: '~/.vimrc'}
    - {src: '~/.dot-files/vim/vim',           dest: '~/.vim'}
    - {src: '~/.dot-files/tmux/tmux.conf',    dest: '~/.tmux.conf'}
    - {src: '~/.dot-files/pycharm/ideavimrc', dest: '~/.ideavimrc'}

- name: installing vim plugins
  command: vim +PluginInstall +qall
  args:
    creates: ~/.dot-files/vim/vim/bundle/ctrlp.vim

- name: making vim the default text editor
  copy:
    src: defaults.list
    dest: ~/.local/share/applications/defaults.list

- name: installing vagrant guest-additions plugin
  command: vagrant plugin install vagrant-vbguest
  args:
    creates: ~/.vagrant.d/gems/gems/vagrant-vbguest-*

- name: applying custom keyboard shortcuts
  copy:
    src: xfce4-keyboard-shortcuts.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/

- name: copying compiz settings to ansible file cache
  copy:
    src: compiz.profile
    dest: '{{ ansible_file_cache }}'
  register: new_compiz_settings

- name: import compiz settings
  command: python -c "import compizconfig; compizconfig.Context().Import('{{ ansible_file_cache }}/compiz.profile')"
  when: new_compiz_settings | changed

- name: make compiz the default windows manager
  copy:
    src: xfce4-session.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/
