---

- name: reread kernel options
  command: sysctl -p

- name: restart sysstat service
  service:
    name: sysstat
    state: restarted

- name: restart tlp service
  service:
    name: tlp
    state: restarted

- name: reload udev rules
  command: udevadm control --reload-rules
