---

- name: installing common packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - linux-headers-generic
    - python-pip
    - python-apt
    - python-dev
    - python-setuptools
    - zsh

- name: create application specific groups
  group:
    name: '{{ item }}'
    state: present
  with_items:
    - docker
    - plugdev

- name: start using zsh
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh
    groups:
      - docker
      - plugdev
    append: yes

- name: upgrading python package manager
  pip:
    name: pip
    state: latest

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: latest

- name: install ipython
  pip:
    name: ipython
    state: latest

- name: correcting apple aluminum f'n keys
  lineinfile:
    line: options hid_apple fnmode=2
    dest: /etc/modprobe.d/hid_apple.conf
    create: yes
  register: apple_keyboard_mod
  tags:
    - fn-keyboard

- name: recompiling initramfs for apple's f'n keyboard
  command: update-initramfs -u -k all
  when: apple_keyboard_mod | changed
  tags:
    - fn-keyboard

- name: adding custom ppa's, thanks guys!
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - ppa:webupd8team/java
    - ppa:linrunner/tlp
    - ppa:nathan-renniewaldock/flux
    - ppa:bitcoin/bitcoin

- name: adding third party keys to aptitude
  apt_key:
    url: '{{ item }}'
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox.asc
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://download.docker.com/linux/ubuntu/gpg

- name: adding third party repositories to aptitude
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: accepting java's evil licenses
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: installing useful packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https
    - awscli
    - autojump
    - bitcoin-qt
    - ca-certificates
    - cloc
    - cmake
    - compiz
    - compizconfig-settings-manager
    - compiz-plugins
    - cups-pdf
    - curl
    - docker-ce
    - dosbox
    - exfat-fuse
    - fluxgui
    - gcolor2
    - gimp
    - gnuradio
    - google-chrome-stable
    - gparted
    - gtk-recordmydesktop
    - htop
    - imagemagick
    - indicator-multiload
    - iotop
    - nmap
    - oracle-java8-installer
    - python3-dev
    - python-lxml
    - python-compizconfig
    - python-gpgme
    - software-properties-common
    - sqlite3
    - sshfs
    - sysstat
    - tlp
    - tmux
    - tor
    - tor-arm
    - tree
    - vagrant
    - vim-gnome
    - virtualbox-5.1
    - vlc
    - weechat
    - whois
    - wireshark
    - xclip
    - xfce4-goodies
    - xscreensaver
    - xscreensaver-data
    - xscreensaver-data-extra
    - xscreensaver-screensaver-bsod
    - xubuntu-restricted-extras
    - zeal

- name: installing sdr fun
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - hackrf
    - mono-complete
    - libportaudio2
    - librtlsdr0

- name: hackeRF rules!
  copy:
    src: 52-hackrf.rules
    dest: /etc/udev/rules.d/52-hackrf.rules
    owner: root
    group: root
    mode: 0600

- name: don't allow hackRF any sleep
  lineinfile:
    path: /etc/default/tlp
    line: USB_BLACKLIST="1d50:6089 1d50:604b"
  notify: restart tlp service

- name: installing missing bluetooth module
  apt:
    name: pulseaudio-module-bluetooth
    state: latest
  register: bt_fix
  tags: bt

- command: pactl load-module module-bluetooth-discover
  when: bt_fix | change
  tags: bt

- name: removing xubuntu's light-locker screensaver
  apt:
    name: light-locker
    state: absent

- name: setting fs.inotify watches to 100,000 to make dropbox happy
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^fs.inotify.max_user_watches=
    line: fs.inotify.max_user_watches=100000
  notify: reread kernel options

- name: enable sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: ^ENABLED=
    line: ENABLED="true"
  notify: restart sysstat service

- name: copy intel x11 config for chrome
  copy:
    src: 10-intel-chrome.conf
    dest: /usr/share/X11/xorg.conf.d/
    owner: root
    group: root
    mode: 0644
  notify: restart lightdm service
