---

- name: installing common packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - linux-headers-generic
    - python-pip
    - python-apt
    - python-dev
    - python-setuptools
    - zsh

- name: installing global python packages
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - pip
    - ipython
    - httpie

- name: correcting apple aluminum f'n keys
  lineinfile:
    line: options hid_apple fnmode=2
    dest: /etc/modprobe.d/hid_apple.conf
    create: yes
  register: apple_keyboard_mod
  tags:
    - fn-keyboard

- name: recompiling initramfs for apple's f'n keyboard
  command: update-initramfs -u -k all
  when: apple_keyboard_mod is changed
  tags:
    - fn-keyboard

- name: adding custom ppa's, thanks guys!
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - ppa:webupd8team/java       # Java, the easy way
    - ppa:linrunner/tlp          # thinkpad power settings
    - ppa:peek-developers/stable # gif capture recorder
    - ppa:nathan-renniewaldock/flux
    - ppa:graphics-drivers/ppa

- name: adding third party keys to aptitude
  apt_key:
    url: '{{ item }}'
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: adding third party repositories to aptitude
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb https://download.virtualbox.org/virtualbox/debian xenial contrib

- name: accepting java's evil licenses
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: installing useful packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - awscli
    - autojump
    - ca-certificates
    - cewl
    - cloc
    - cmake
    - compiz
    - compizconfig-settings-manager
    - compiz-plugins
    - cups-pdf
    - curl
    - filezilla
    - gimp
    - google-chrome-stable
    - gparted
    - gtk-recordmydesktop
    - htop
    - imagemagick
    - indicator-multiload
    - iotop
    - john
    - libreoffice
    - mercurial
    - nmap
    - npm
    - nvidia-390
    - openvpn
    - oracle-java8-installer
    - peek
    - postgresql
    - postgresql-contrib
    - python-lxml
    - python-compizconfig
    - rdesktop
    - redshift-gtk
    - sqlite3
    - sshfs
    - sysstat
    - tlp
    - tmux
    - tree
    - vim-gnome
    - virtualbox
    - vlc
    - whois
    - wireshark
    - xchat
    - xclip
    - xfce4-goodies
    - xscreensaver
    - xscreensaver-data
    - xscreensaver-data-extra
    - xscreensaver-screensaver-bsod
    - xubuntu-restricted-extras
    - zeal

- name: create wireshark group
  group:
    name: wireshark

- name: removing xubuntu's light-locker screensaver
  apt:
    name: light-locker
    state: absent

- name: setting fs.inotify watches to 100,000 to make dropbox happy
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^fs.inotify.max_user_watches=
    line: fs.inotify.max_user_watches=100000
  notify: reread kernel options

- name: enable sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: ^ENABLED=
    line: ENABLED="true"
  notify: restart sysstat service

- name: add docker apt key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker deb repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: install docker ce
  apt:
    name: docker-ce
    update_cache: yes

- name: install docker python modules
  pip:
    name: docker-compose

- name: install n node package
  npm:
    name: n
    global: yes

- name: copy over lenovo dock udev rules for monitor management
  copy:
    src: 84-thinkpad-dock.rules
    dest: /etc/udev/rules.d/
  notify: reload udev rules

- name: copy over lenovo dock monitor changing script
  template:
    src: monitors.sh.j2
    dest: /usr/local/bin/monitors.sh
