---

- name: installing common packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - linux-headers-generic
    - python-pip
    - python-apt
    - python-dev
    - python-setuptools
    - zsh

- name: start using zsh
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh

- name: upgrading python package manager
  pip:
    name: pip
    state: latest

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: latest

- name: correcting apple aluminum f'n keys
  lineinfile:
    line: options hid_apple fnmode=2
    dest: /etc/modprobe.d/hid_apple.conf
    create: yes
  register: apple_keyboard_mod
  tags:
    - fn-keyboard

- name: recompiling initramfs for apple's f'n keyboard
  command: update-initramfs -u -k all
  when: apple_keyboard_mod | changed
  tags:
    - fn-keyboard

- name: adding custom ppa's, thanks guys!
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - ppa:webupd8team/java
    - ppa:linrunner/tlp
    - ppa:nathan-renniewaldock/flux

- name: adding third party keys to aptitude
  apt_key:
    url: '{{ item }}'
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox.asc
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://download.docker.com/linux/ubuntu/gpg

- name: adding third party repositories to aptitude
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: accepting java's evil licenses
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: installing useful packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https
    - awscli
    - autojump
    - ca-certificates
    - cloc
    - cmake
    - compiz
    - compizconfig-settings-manager
    - compiz-plugins
    - cups-pdf
    - curl
    - docker-ce
    - fluxgui
    - gcolor2
    - gimp
    - google-chrome-stable
    - gparted
    - gtk-recordmydesktop
    - htop
    - imagemagick
    - indicator-multiload
    - iotop
    - nmap
    - oracle-java8-installer
    - python-lxml
    - python-compizconfig
    - python-gpgme
    - software-properties-common
    - sqlite3
    - sshfs
    - sysstat
    - tlp
    - tmux
    - tree
    - vagrant
    - vim-gnome
    - virtualbox-5.1
    - vlc
    - whois
    - wireshark
    - xclip
    - xfce4-goodies
    - xscreensaver
    - xscreensaver-data
    - xscreensaver-data-extra
    - xscreensaver-screensaver-bsod
    - xubuntu-restricted-extras
    - zeal

- name: removing xubuntu's light-locker screensaver
  apt:
    name: light-locker
    state: absent

- name: setting fs.inotify watches to 100,000 to make dropbox happy
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: ^fs.inotify.max_user_watches=
    line: fs.inotify.max_user_watches=100000
  notify: reread kernel options

- name: enable sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: ^ENABLED=
    line: ENABLED="true"
  notify: restart sysstat service
