---

- name: adding apt-key for docker repository
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: adding docker repository to aptitude
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-wily main

- name: installing docker with extra kernel modules
  apt:
    state: latest
    name: '{{ item }}'
  with_items:
    - 'linux-image-extra-{{ ansible_kernel }}'
    - docker-engine

- name: adding user to docker group
  user:
    name: '{{ user_name }}'
    groups: docker
    append: yes
